// <auto-generated />
using System;
using FluentMusic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FluentMusic.Data.Migrations
{
    [DbContext(typeof(FluentMusicDbContext))]
    partial class FluentMusicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.19074.3");

            modelBuilder.Entity("FluentMusic.Data.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlbumCover");

                    b.Property<long?>("ArtistId");

                    b.Property<string>("ArtworkPath");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("FluentMusic.Data.Artist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("FluentMusic.Data.Folder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("ModifiedDate");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("FluentMusic.Data.FolderTrack", b =>
                {
                    b.Property<long>("FolderTrackId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("FolderId");

                    b.Property<long?>("TrackId");

                    b.HasKey("FolderTrackId");

                    b.HasIndex("FolderId");

                    b.HasIndex("TrackId");

                    b.ToTable("FolderTracks");
                });

            modelBuilder.Entity("FluentMusic.Data.IndexingTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.ToTable("IndexingTracks");
                });

            modelBuilder.Entity("FluentMusic.Data.RemovingTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.ToTable("RemovingTracks");
                });

            modelBuilder.Entity("FluentMusic.Data.Track", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AlbumId");

                    b.Property<long?>("ArtistId");

                    b.Property<long?>("BitRate");

                    b.Property<long>("DateAdded");

                    b.Property<long>("DateFileCreated");

                    b.Property<long>("DateFileModified");

                    b.Property<long?>("DateLastPlayed");

                    b.Property<long>("DateLastSynced");

                    b.Property<long?>("DiscCount");

                    b.Property<long?>("DiscNumber");

                    b.Property<TimeSpan?>("Duration");

                    b.Property<string>("FileName");

                    b.Property<ulong?>("FileSize");

                    b.Property<long?>("FolderId");

                    b.Property<string>("Genres");

                    b.Property<long?>("HasLyrics");

                    b.Property<string>("IndexingFailureReason");

                    b.Property<long?>("IndexingSuccess");

                    b.Property<long?>("Love");

                    b.Property<string>("MimeType");

                    b.Property<long?>("NeedsAlbumArtworkIndexing");

                    b.Property<long?>("NeedsIndexing");

                    b.Property<string>("Path");

                    b.Property<long?>("PlayCount");

                    b.Property<long?>("Rating");

                    b.Property<string>("SafePath");

                    b.Property<long?>("SampleRate");

                    b.Property<long?>("SkipCount");

                    b.Property<long?>("TrackCount");

                    b.Property<long?>("TrackNumber");

                    b.Property<string>("TrackTitle");

                    b.Property<long?>("Year");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("FolderId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("FluentMusic.Data.Album", b =>
                {
                    b.HasOne("FluentMusic.Data.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId");
                });

            modelBuilder.Entity("FluentMusic.Data.FolderTrack", b =>
                {
                    b.HasOne("FluentMusic.Data.Folder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId");

                    b.HasOne("FluentMusic.Data.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId");
                });

            modelBuilder.Entity("FluentMusic.Data.Track", b =>
                {
                    b.HasOne("FluentMusic.Data.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId");

                    b.HasOne("FluentMusic.Data.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId");

                    b.HasOne("FluentMusic.Data.Folder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId");
                });
#pragma warning restore 612, 618
        }
    }
}
